language: java

env: 
  - TARGET=neko
  - TARGET=html5
matrix:
  allow_failures:
    - env: "TARGET=neko"

before_install:
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt-get install software-properties-common -y
  - sudo apt-get install apt-file -y
  - sudo apt-get install libgc-dev libzip-dev libpcre3-dev -y 
  - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
  - sudo apt-get update                                # pull info from ppa
  - sudo apt-get install haxe -y                       # install haxe (and neko)
  - sudo apt-get install gcc-multilib g++-multilib -y
  - mkdir ~/haxelib
  - haxelib -notimeout setup ~/haxelib 
  - haxelib -notimeout install swf
  - haxelib -notimeout install neko
  - haxelib -notimeout install lime
  - haxelib -notimeout install openfl
  - haxelib git babylonhx https://github.com/babylonhx/babylonHX.git
script:
  - cd ./tests
  - haxe compile.hxml
  branches:
      only:
          - master